#!/bin/sh
#
# 40autorandr: Change autorandr profile on thaw/resume
exec > /var/log/autorandr.log 2>&1

# detect if we are being called as 40auto-disper or 40autorandr
detect_display()
{
	for X in /tmp/.X11-unix/X*; do
		D="${X##/tmp/.X11-unix/X}"
		user=`w -h | awk -vD="$D" '$2 ~ ":"D {print $1}'`
		echo "Checking $X -- $D - $user"
		if [ x"$user" != x"" ]; then
			echo "AUTORANDR $D - $user"
			export DISPLAY=":$D"
			/bin/su -c "autorandr -c" "$user"
		fi
	done
	echo "Done"
}

case "$1" in
	thaw|resume)
		detect_display
		;;
esac
